services:
  api10:
    build: .
    depends_on:
      teamcity10:
        condition: service_healthy
    links:
      - teamcity10
    command: ./run-test.sh -host=teamcity10
  teamcity10:
    build: test10
    ports:
      - 8111:8111
    volumes:
      - ./test10/teamcity:/test-data
    healthcheck:
      test: ["CMD-SHELL", "docker logs $(hostname) 2>&1 | grep -q 'TeamCity is running in professional mode'"]
      interval: 30s
      timeout: 5s
      retries: 10
  # agent10:
  #   image: jetbrains/teamcity-agent:2025.03.3
  #   depends_on:
  #     - teamcity10
  #   links:
  #     - teamcity10
  #   environment:
  #     SERVER_URL: http://teamcity10:8111/
  #   volumes:
  #     - ./test10/agent:/data/teamcity_agent/conf
  #     - /var/run/docker.sock:/var/run/docker.sock
